spring:
  profiles:
    active: local
---
spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:db-init/schema.sql
  output:
    ansi:
      enabled: always
  application:
    name: webflux-coroutine
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:3306/sample
    username: user
    password: 1234

api:
  externalUrl: "http://localhost:8080"

logging:
  level:
    me.snowlight: debug
    org.springframework.r2dbc.core: debug
    org.springframework.r2dbc.connection: debug
    org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler: off
    org.springframework.http.HttpLogging: off
    org.springframework.web.HttpLogging: off
  pattern:
    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%logger|%blue(\\(%F:%L\\))|%msg%n"
---
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:pool:h2:file:///./sample
  sql:
    init:
      mode: always
server:
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    include-stacktrace: always
---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:pool:h2:mem://localhost/sample
  sql:
    init:
      mode: embedded
---
spring:
  config:
    activate:
      on-profile: stress
  output:
    ansi:
      enabled: never
logging:
  level:
    me.snowlight.springkotlincoroutine: debug
    org.springframework.r2dbc.core: off
    org.springframework.r2dbc.connection: off
---
spring:
  config:
    activate:
      on-profile: prod

server:
  error:
    include-binding-errors: never
    include-stacktrace: never