spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:db-init/schema.sql
  output:
    ansi:
      enabled: always
  application:
    name: webflux-coroutine
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:3306/sample
    username: user
    password: 1234